context:
  name: simpleaudio
  version: "1.0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 691c88649243544db717e7edf6a9831df112104e1aefb5f6038a5d071e8cf41d

build:
  script: python -m pip install . -vv
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - if: linux
      then:
        - alsa-lib
  run:
    - python
    - if: linux
      then:
        - alsa-lib

tests:
  - python:
      imports:
      - simpleaudio
      pip_check: true

about:
  homepage: https://github.com/hamiltron/py-simple-audio
  summary: Simple, asynchronous audio playback for Python 3
  description: Simple, asynchronous audio playback for Python 3.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - raybellwaves
